clusterAuditor:
  enabled: false

gatekeeper:
  enabled: false

istio:
  ingressGateways:
    public-ingressgateway:
      kubernetesResourceSpec:
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  values:
    istiod:
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      hpaSpec:
        maxReplicas: 1

istiooperator:
  values:
    operator:
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "256Mi"

jaeger:
  enabled: false

kiali:
  enabled: false

monitoring:
  enabled: false

twistlock:
  enabled: false
